namespace NeoServiceLayer.Shared.Models.Attestation
{
    /// <summary>
    /// Represents attestation evidence generated by an enclave.
    /// </summary>
    public class AttestationEvidence
    {
        /// <summary>
        /// Gets or sets the enclave-held data that was included in the evidence.
        /// </summary>
        public byte[] EnclaveHeldData { get; set; }

        /// <summary>
        /// Gets or sets the format of the evidence.
        /// </summary>
        public string Format { get; set; }

        /// <summary>
        /// Gets or sets the evidence data.
        /// </summary>
        public byte[] Evidence { get; set; }

        /// <summary>
        /// Gets or sets the endorsements data.
        /// </summary>
        public byte[] Endorsements { get; set; }
    }
}
