apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: neo-postgres-pvc
  namespace: neo-service-layer
  labels:
    app: neo-postgres
    component: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: fast-ssd
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: neo-postgres-backup-pvc
  namespace: neo-service-layer
  labels:
    app: neo-postgres
    component: backup
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
  storageClassName: standard