version: '3.8'

services:
  neo-service-layer:
    image: jinghuiliao/neo-service-layer:latest
    container_name: neo-service-layer-dev
    ports:
      - "8080:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:-development-jwt-secret-key-for-testing-only-32chars}
      - NEO_ALLOW_SGX_SIMULATION=true
      - ASPNETCORE_LOGGING__LOGLEVEL__DEFAULT=Information
      - ASPNETCORE_LOGGING__LOGLEVEL__MICROSOFT=Warning
    volumes:
      - neo-dev-data:/app/data
      - neo-dev-logs:/var/log/neo-service-layer
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "${SERVICE_ENDPOINT_5000:-http://localhost:5000}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - neo-dev-network

volumes:
  neo-dev-data:
    driver: local
  neo-dev-logs:
    driver: local

networks:
  neo-dev-network:
    driver: bridge