# Neo Service Layer - Production Deployment
# This file combines all phases for production deployment

version: '3.8'

services:
  # Phase 1 - Infrastructure Services
  neo-postgres:
    image: postgres:16-alpine
    container_name: neo-postgres
    environment:
      POSTGRES_DB: neo_service_layer
      POSTGRES_USER: neo_service_user
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - neo-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U neo_service_user"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  neo-redis:
    image: redis:7-alpine
    container_name: neo-redis
    command: redis-server --requirepass ${DB_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - neo-network
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "-a", "${DB_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

networks:
  neo-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local