version: '3.8'

services:
  neo-service-layer:
    image: jinghuiliao/neo-service-layer:latest
    container_name: neo-service-layer
    ports:
      - "0.0.0.0:8080:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
      # JWT_SECRET_KEY must be set via environment variable for security
      # Example: export JWT_SECRET_KEY=$(openssl rand -base64 32)
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:?JWT_SECRET_KEY environment variable is required}
      - NEO_ALLOW_SGX_SIMULATION=true
      - DOTNET_ENVIRONMENT=Development
      - SSL_CERT_PATH=
      # Configure CORS for your specific domain in production
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS:-http://localhost:3000,http://localhost:8080}
      - ASPNETCORE_CORS__ALLOWANYORIGIN=true
      - ASPNETCORE_CORS__ALLOWANYMETHOD=true
      - ASPNETCORE_CORS__ALLOWANYHEADER=true
    volumes:
      - neo-data:/app/data
      - neo-logs:/var/log/neo-service-layer
      - neo-config:/app/config
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "${SERVICE_HTTP_5000:-http://${SERVICE_HOST_5000:-localhost:5000}}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - neo-network

  # Optional: Add a reverse proxy for production deployments
  nginx:
    image: nginx:alpine
    container_name: neo-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./config/ssl:/etc/nginx/ssl:ro
    depends_on:
      - neo-service-layer
    restart: unless-stopped
    networks:
      - neo-network
    profiles:
      - production

volumes:
  neo-data:
    driver: local
  neo-logs:
    driver: local
  neo-config:
    driver: local

networks:
  neo-network:
    driver: bridge