version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: neo-postgres-test
    environment:
      - POSTGRES_DB=neo_service_layer
      - POSTGRES_USER=neo_service_user
      - POSTGRES_PASSWORD=SecurePass123!
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U neo_service_user"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: neo-redis-test
    command: redis-server --requirepass RedisPass123!
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
