version: '3.8'

services:
  neo-service-occlum:
    build:
      context: .
      dockerfile: Dockerfile.occlum
    image: neo-service-layer:occlum
    container_name: neo-service-occlum
    devices:
      - /dev/sgx_enclave:/dev/sgx_enclave
      - /dev/sgx_provision:/dev/sgx_provision
    volumes:
      - /var/run/aesmd:/var/run/aesmd
      - ./src:/workspace/src:ro
      - ./tests:/workspace/tests:ro
    ports:
      - "5000:5000"
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000;https://+:5001
      - OCCLUM_LOG_LEVEL=debug
    networks:
      - neo-network

  neo-service-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    image: neo-service-layer:dev
    container_name: neo-service-dev
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
    ports:
      - "5002:5000"
      - "5003:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_USE_POLLING_FILE_WATCHER=true
      - DOTNET_WATCH_RESTART_ON_RUDE_EDIT=true
    command: ["dotnet", "watch", "run", "--project", "/app/src/Api/NeoServiceLayer.Api/NeoServiceLayer.Api.csproj"]
    networks:
      - neo-network

networks:
  neo-network:
    driver: bridge