# NGINX Ingress Controller Configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configuration
  namespace: ingress-nginx
data:
  # Global settings
  proxy-body-size: "100m"
  proxy-connect-timeout: "30"
  proxy-read-timeout: "300"
  proxy-send-timeout: "300"
  
  # SSL/TLS configuration
  ssl-protocols: "TLSv1.2 TLSv1.3"
  ssl-ciphers: "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384"
  ssl-prefer-server-ciphers: "true"
  ssl-session-cache: "true"
  ssl-session-cache-size: "10m"
  ssl-session-timeout: "10m"
  ssl-buffer-size: "16k"
  
  # HTTP/2 settings
  http2-max-field-size: "16k"
  http2-max-header-size: "32k"
  http2-max-requests: "1000"
  
  # Security headers
  add-headers: "neo-service-layer/custom-headers"
  hide-headers: "X-Powered-By,Server"
  
  # Rate limiting
  limit-req-status-code: "429"
  limit-conn-status-code: "429"
  
  # Logging
  log-format-upstream: '$remote_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent" "$http_x_forwarded_for" $request_id $request_time $upstream_response_time'
  access-log-path: "/var/log/nginx/access.log"
  error-log-path: "/var/log/nginx/error.log"
  error-log-level: "error"
  
  # Performance tuning
  worker-processes: "auto"
  worker-cpu-affinity: "auto"
  worker-connections: "4096"
  worker-rlimit-nofile: "65536"
  keepalive: "32"
  keepalive-timeout: "65"
  keepalive-requests: "100"
  
  # Gzip compression
  use-gzip: "true"
  gzip-level: "5"
  gzip-min-length: "256"
  gzip-types: "application/atom+xml application/javascript application/x-javascript application/json application/rss+xml application/vnd.ms-fontobject application/x-font-ttf application/x-web-app-manifest+json application/xhtml+xml application/xml font/opentype image/svg+xml image/x-icon text/css text/plain text/x-component"
  
  # Brotli compression
  enable-brotli: "true"
  brotli-level: "4"
  brotli-types: "text/xml image/svg+xml application/x-font-ttf image/vnd.microsoft.icon application/x-font-opentype application/json font/eot application/vnd.ms-fontobject application/javascript font/otf application/xml application/xhtml+xml text/javascript application/x-javascript text/plain application/x-font-truetype application/xml+rss image/x-icon font/ttf text/css image/x-win-bitmap"
  
  # Custom error pages
  custom-http-errors: "404,503"
  
---
# Custom headers ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-headers
  namespace: neo-service-layer
data:
  X-Content-Type-Options: "nosniff"
  X-Frame-Options: "DENY"
  X-XSS-Protection: "1; mode=block"
  Referrer-Policy: "strict-origin-when-cross-origin"
  Permissions-Policy: "geolocation=(), microphone=(), camera=()"
  X-Service: "Neo-Service-Layer"

---
# Basic auth secret for monitoring
apiVersion: v1
kind: Secret
metadata:
  name: monitoring-basic-auth
  namespace: neo-service-layer
type: kubernetes.io/basic-auth
stringData:
  auth: |
    # admin:$ADMIN_PASSWORD (use htpasswd to generate)
    admin:$2y$10$YourHashedPasswordHere
    # monitoring:$MONITORING_PASSWORD
    monitoring:$2y$10$YourHashedPasswordHere

---
# Custom error pages
apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-error-pages
  namespace: ingress-nginx
data:
  404.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>404 - Not Found</title>
        <style>
            body { font-family: Arial, sans-serif; text-align: center; padding: 50px; background-color: #f5f5f5; }
            h1 { color: #333; font-size: 48px; margin-bottom: 10px; }
            p { color: #666; font-size: 18px; }
            a { color: #007bff; text-decoration: none; }
            a:hover { text-decoration: underline; }
            .container { background-color: white; padding: 40px; border-radius: 10px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); display: inline-block; }
        </style>
    </head>
    <body>
        <div class="container">
            <h1>404</h1>
            <p>The requested resource was not found.</p>
            <p><a href="/">Return to API Documentation</a></p>
        </div>
    </body>
    </html>
  
  503.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>503 - Service Unavailable</title>
        <style>
            body { font-family: Arial, sans-serif; text-align: center; padding: 50px; background-color: #f5f5f5; }
            h1 { color: #dc3545; font-size: 48px; margin-bottom: 10px; }
            p { color: #666; font-size: 18px; }
            .container { background-color: white; padding: 40px; border-radius: 10px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); display: inline-block; }
            .status { margin-top: 20px; font-size: 14px; color: #999; }
        </style>
    </head>
    <body>
        <div class="container">
            <h1>503</h1>
            <p>Service temporarily unavailable. Please try again later.</p>
            <p class="status">Our team has been notified and is working on the issue.</p>
        </div>
    </body>
    </html>