apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default
  namespace: neo-services
spec:
  mtls:
    mode: STRICT

---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: neo-auth-service-authz
  namespace: neo-services
spec:
  selector:
    matchLabels:
      app: neo-auth-service
  rules:
  # Allow public authentication endpoints
  - from:
    - source:
        namespaces: ["istio-system", "neo-infrastructure"]
    to:
    - operation:
        methods: ["GET", "POST", "OPTIONS"]
        paths: ["/api/auth/login", "/api/auth/register", "/health/*"]
  
  # Allow inter-service communication
  - from:
    - source:
        namespaces: ["neo-services"]
    to:
    - operation:
        methods: ["POST"]
        paths: ["/api/auth/validate"]

---
apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: neo-jwt-auth
  namespace: neo-services
spec:
  selector:
    matchLabels:
      auth-required: "true"
  jwtRules:
  - issuer: "neo-auth-service"
    audiences:
    - "neo-service-layer"
    jwksUri: "http://neo-auth-service.neo-services.svc.cluster.local/api/auth/.well-known/jwks.json"
    fromHeaders:
    - name: "Authorization"
      prefix: "Bearer "