apiVersion: v1
kind: Secret
metadata:
  name: neo-service-secrets
  namespace: neo-service-layer
type: Opaque
stringData:
  # Database Credentials
  Database__Password: "CHANGE_ME_IN_PRODUCTION"
  # Redis Password
  Redis__Password: "CHANGE_ME_IN_PRODUCTION"
  # RabbitMQ Password
  RabbitMQ__Password: "CHANGE_ME_IN_PRODUCTION"
  # JWT Configuration
  Jwt__Key: "CHANGE_ME_TO_A_SECURE_256_BIT_KEY_IN_PRODUCTION"
  Jwt__Issuer: "NeoServiceLayer"
  Jwt__Audience: "NeoServiceLayerClients"
  # API Keys
  Oracle__ApiKey: "CHANGE_ME_IN_PRODUCTION"
  CrossChain__ApiKey: "CHANGE_ME_IN_PRODUCTION"
  # Encryption Keys
  Encryption__Key: "CHANGE_ME_TO_A_SECURE_256_BIT_KEY_IN_PRODUCTION"
  Encryption__IV: "CHANGE_ME_TO_A_SECURE_128_BIT_IV_IN_PRODUCTION"