apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: neo-service-layer-neo-node-pvc
  namespace: neo-service-layer
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: standard
