global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'neo-service-layer'
    environment: 'production'

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Neo Service Layer API
  - job_name: 'neo-service-api'
    static_configs:
      - targets: ['neo-service-api:9090']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 10s
    honor_labels: true
    params:
      format: ['prometheus']

  # System metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s

  # PostgreSQL metrics
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s

  # Redis metrics
  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s

  # RabbitMQ metrics
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']
    scrape_interval: 30s

  # Nginx metrics
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']
    scrape_interval: 30s

  # Elasticsearch metrics
  - job_name: 'elasticsearch'
    static_configs:
      - targets: ['elasticsearch-exporter:9114']
    scrape_interval: 30s

  # Custom application metrics
  - job_name: 'neo-service-custom'
    static_configs:
      - targets: ['neo-service-api:9090']
    metrics_path: '/metrics/custom'
    scrape_interval: 30s
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'neo_service_.*'
        target_label: __name__
        replacement: '${1}'

  # Health check metrics
  - job_name: 'neo-service-health'
    static_configs:
      - targets: ['neo-service-api:5000']
    metrics_path: '/health/metrics'
    scrape_interval: 60s
    scrape_timeout: 30s

  # Blockchain metrics
  - job_name: 'blockchain-metrics'
    static_configs:
      - targets: ['neo-service-api:9090']
    metrics_path: '/metrics/blockchain'
    scrape_interval: 60s
    params:
      module: ['neo_n3', 'neo_x']

  # AI service metrics
  - job_name: 'ai-services'
    static_configs:
      - targets: ['neo-service-api:9090']
    metrics_path: '/metrics/ai'
    scrape_interval: 30s
    honor_labels: true

  # Security metrics
  - job_name: 'security-metrics'
    static_configs:
      - targets: ['neo-service-api:9090']
    metrics_path: '/metrics/security'
    scrape_interval: 60s
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'security_.*'
        target_label: component
        replacement: 'security'

# Remote write configuration for long-term storage
remote_write:
  - url: "http://prometheus-remote-storage:9201/write"
    queue_config:
      max_samples_per_send: 1000
      max_shards: 200
      capacity: 2500

# Remote read configuration
remote_read:
  - url: "http://prometheus-remote-storage:9201/read"
    read_recent: true 