using System;

namespace NeoServiceLayer.Tee.Host.Models
{
    /// <summary>
    /// Represents a record of a random number generation.
    /// </summary>
    public class RandomNumberGeneration
    {
        /// <summary>
        /// Gets or sets the generated random number.
        /// </summary>
        public ulong RandomNumber { get; set; }

        /// <summary>
        /// Gets or sets the minimum value of the range.
        /// </summary>
        public ulong Min { get; set; }

        /// <summary>
        /// Gets or sets the maximum value of the range.
        /// </summary>
        public ulong Max { get; set; }

        /// <summary>
        /// Gets or sets the ID of the user who requested the random number.
        /// </summary>
        public string UserId { get; set; }

        /// <summary>
        /// Gets or sets the ID of the request.
        /// </summary>
        public string RequestId { get; set; }

        /// <summary>
        /// Gets or sets the UNIX timestamp (in seconds) when the random number was generated.
        /// </summary>
        public long Timestamp { get; set; }

        /// <summary>
        /// Gets or sets the proof that the random number was generated by the enclave.
        /// </summary>
        public string Proof { get; set; }
    }
} 