groups:
  - name: neo_service_layer_alerts
    interval: 30s
    rules:
      # Service availability alerts
      - alert: ServiceDown
        expr: up{job=~"neo-.*"} == 0
        for: 2m
        labels:
          severity: critical
          team: platform
        annotations:
          summary: "Service {{ $labels.job }} is down"
          description: "{{ $labels.job }} has been down for more than 2 minutes"

      - alert: HighErrorRate
        expr: |
          (
            sum(rate(http_requests_total{status=~"5.."}[5m])) by (service)
            /
            sum(rate(http_requests_total[5m])) by (service)
          ) > 0.05
        for: 5m
        labels:
          severity: warning
          team: platform
        annotations:
          summary: "High error rate for {{ $labels.service }}"
          description: "Error rate is {{ $value | humanizePercentage }} for {{ $labels.service }}"

      # Performance alerts
      - alert: HighResponseTime
        expr: |
          histogram_quantile(0.95,
            sum(rate(http_request_duration_seconds_bucket[5m])) by (service, le)
          ) > 1
        for: 5m
        labels:
          severity: warning
          team: platform
        annotations:
          summary: "High response time for {{ $labels.service }}"
          description: "95th percentile response time is {{ $value }}s for {{ $labels.service }}"

      - alert: HighCPUUsage
        expr: |
          (
            100 - (avg by (instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100)
          ) > 80
        for: 10m
        labels:
          severity: warning
          team: infrastructure
        annotations:
          summary: "High CPU usage on {{ $labels.instance }}"
          description: "CPU usage is {{ $value }}% on {{ $labels.instance }}"

      - alert: HighMemoryUsage
        expr: |
          (
            (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100
          ) > 85
        for: 10m
        labels:
          severity: warning
          team: infrastructure
        annotations:
          summary: "High memory usage on {{ $labels.instance }}"
          description: "Memory usage is {{ $value }}% on {{ $labels.instance }}"

      # Database alerts
      - alert: DatabaseConnectionPoolExhausted
        expr: |
          (
            neo_database_connections_active / neo_database_connections_max
          ) > 0.9
        for: 5m
        labels:
          severity: critical
          team: database
        annotations:
          summary: "Database connection pool nearly exhausted"
          description: "{{ $value | humanizePercentage }} of database connections are in use"

      - alert: DatabaseSlowQueries
        expr: |
          rate(neo_database_query_duration_seconds_sum[5m]) > 1
        for: 5m
        labels:
          severity: warning
          team: database
        annotations:
          summary: "Database queries are slow"
          description: "Average query duration is {{ $value }}s"

      # Redis alerts
      - alert: RedisDown
        expr: redis_up == 0
        for: 2m
        labels:
          severity: critical
          team: platform
        annotations:
          summary: "Redis is down"
          description: "Redis has been down for more than 2 minutes"

      - alert: RedisHighMemoryUsage
        expr: |
          redis_memory_used_bytes / redis_memory_max_bytes > 0.9
        for: 5m
        labels:
          severity: warning
          team: platform
        annotations:
          summary: "Redis memory usage is high"
          description: "Redis is using {{ $value | humanizePercentage }} of max memory"

      # Rate limiting alerts
      - alert: HighRateLimitRejections
        expr: |
          sum(rate(neo_rate_limit_rejected_total[5m])) by (endpoint) > 10
        for: 5m
        labels:
          severity: warning
          team: platform
        annotations:
          summary: "High rate of rate limit rejections for {{ $labels.endpoint }}"
          description: "{{ $value }} requests per second are being rate limited"

      # Circuit breaker alerts
      - alert: CircuitBreakerOpen
        expr: neo_circuit_breaker_state{state="open"} == 1
        for: 1m
        labels:
          severity: warning
          team: platform
        annotations:
          summary: "Circuit breaker is open for {{ $labels.service }}"
          description: "Circuit breaker for {{ $labels.service }} has been open for more than 1 minute"

      # SGX/TEE alerts
      - alert: EnclaveNotHealthy
        expr: neo_enclave_health == 0
        for: 5m
        labels:
          severity: critical
          team: security
        annotations:
          summary: "SGX Enclave is not healthy"
          description: "SGX Enclave health check has been failing for 5 minutes"

      - alert: EnclaveAttestationFailure
        expr: |
          increase(neo_enclave_attestation_failures_total[5m]) > 0
        labels:
          severity: critical
          team: security
        annotations:
          summary: "SGX Enclave attestation failures detected"
          description: "{{ $value }} attestation failures in the last 5 minutes"

      # Business metrics alerts
      - alert: LowTransactionThroughput
        expr: |
          sum(rate(neo_transactions_processed_total[5m])) < 10
        for: 10m
        labels:
          severity: warning
          team: business
        annotations:
          summary: "Transaction throughput is low"
          description: "Only {{ $value }} transactions per second being processed"

      - alert: HighTransactionFailureRate
        expr: |
          (
            sum(rate(neo_transactions_failed_total[5m]))
            /
            sum(rate(neo_transactions_total[5m]))
          ) > 0.1
        for: 5m
        labels:
          severity: warning
          team: business
        annotations:
          summary: "High transaction failure rate"
          description: "{{ $value | humanizePercentage }} of transactions are failing"