global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'neo-service-layer'

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # API Gateway metrics
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:80']
    metrics_path: '/metrics'

  # Service discovery for all Neo services
  - job_name: 'neo-services'
    consul_sd_configs:
      - server: 'consul:8500'
        services: []
    relabel_configs:
      - source_labels: [__meta_consul_service]
        regex: '(.*)-service'
        target_label: service_name
      - source_labels: [__meta_consul_service_metadata_version]
        target_label: service_version
      - source_labels: [__meta_consul_service_metadata_capabilities]
        target_label: service_capabilities
      - source_labels: [__address__]
        target_label: __address__
        regex: '([^:]+):.*'
        replacement: '${1}:80'

  # Infrastructure monitoring
  - job_name: 'consul'
    static_configs:
      - targets: ['consul:8500']
    metrics_path: '/v1/agent/metrics'
    params:
      format: ['prometheus']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']

  # Node exporter for container metrics
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - '/etc/prometheus/alerts/*.yml'