apiVersion: v2
name: neo-service-layer
description: A Helm chart for Neo Service Layer microservices
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - neo
  - blockchain
  - microservices
home: https://github.com/your-org/neo-service-layer
sources:
  - https://github.com/your-org/neo-service-layer
maintainers:
  - name: Neo Service Layer Team
    email: team@neoservicelayer.com
dependencies:
  - name: postgresql
    version: "13.2.0"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
  - name: redis
    version: "18.0.0"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
  - name: rabbitmq
    version: "12.0.0"
    repository: "https://charts.bitnami.com/bitnami"
    condition: rabbitmq.enabled
  - name: prometheus
    version: "19.0.0"
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: prometheus.enabled
  - name: grafana
    version: "7.0.0"
    repository: "https://grafana.github.io/helm-charts"
    condition: grafana.enabled