version: '3.8'

services:
  neo-service-layer:
    build:
      context: ../../
      dockerfile: docker/occlum-test/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
      - Tee__SimulationMode=true
      - Tee__OcclumSupport=true
      - Tee__OcclumInstanceDir=/occlum_instance
      - Tee__OcclumLogLevel=info
    volumes:
      - occlum_instance:/occlum_instance
    restart: unless-stopped

volumes:
  occlum_instance:
