version: '3.8'

services:
  neo-service-layer:
    build:
      context: ../..
      dockerfile: docker/occlum/Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000;https://+:5001
      - Tee__Type=Occlum
      - Tee__SimulationMode=true
      - OCCLUM_SIMULATION=1
      - Tee__EnclavePath=/occlum_instance/image/lib/libneoserviceenclave.so
      - Tee__Debug=true
      - Tee__Occlum__InstanceDir=/occlum_instance
      - Tee__Occlum__LogLevel=debug
      - Tee__Occlum__NodeJsPath=/bin/node
      - Tee__Occlum__TempDir=/tmp
      - Tee__Occlum__EnableDebugMode=true
      - Tee__Occlum__MaxMemoryMB=1024
      - Tee__Occlum__MaxThreads=32
      - Tee__Occlum__MaxProcesses=16
      - Tee__Occlum__MaxExecutionTimeSeconds=60
    volumes:
      - ../../src:/app/src
      - ../../tests:/app/tests
      - occlum_instance:/occlum_instance
    depends_on:
      - storage
    networks:
      - neo-network

  storage:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - neo-network

networks:
  neo-network:
    driver: bridge

volumes:
  occlum_instance:
