[build]
  # Deploy static site for now - skip Next.js build
  command = "echo 'Deploying static site'"
  publish = "."
  
[build.environment]
  NODE_VERSION = "18.18.0"

# Headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' https:; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cdn.jsdelivr.net https://cdnjs.cloudflare.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://cdnjs.cloudflare.com; font-src 'self' https://fonts.gstatic.com https://cdnjs.cloudflare.com; img-src 'self' data: https:; connect-src 'self' https: wss:;"

# SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200