[build]
  # Build command (not needed for static site)
  command = ""
  
  # Directory to publish
  publish = "."
  
  # Functions directory (if needed in future)
  functions = "netlify/functions"

[build.environment]
  # Environment variables
  NODE_VERSION = "18"

# Redirect rules
[[redirects]]
  # Redirect /docs/* to documentation pages
  from = "/docs/*"
  to = "/docs/:splat"
  status = 200

[[redirects]]
  # SPA fallback for any unmatched routes
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Performance headers
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.ico"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Form handling (for future contact forms)
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true

# Plugin configuration
[[plugins]]
  package = "netlify-plugin-minify-html"
  
  [plugins.inputs]
    contexts = ["production"]

# Edge functions (for future use)
# [[edge_functions]]
#   path = "/api/*"
#   function = "api-handler"

# Dev server configuration
[dev]
  command = "python3 -m http.server 8000"
  port = 8000
  publish = "."
  autoLaunch = true

# Context-specific settings
[context.production]
  [context.production.environment]
    NODE_ENV = "production"

[context.deploy-preview]
  [context.deploy-preview.environment]
    NODE_ENV = "development"

[context.branch-deploy]
  [context.branch-deploy.environment]
    NODE_ENV = "development"