[build]
  # Deploy static site for now - skip Next.js build
  command = "echo 'Deploying static site'"
  publish = "."
  
[build.environment]
  NODE_VERSION = "18.18.0"

# Headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200