apiVersion: v1
kind: Service
metadata:
  name: consul
  namespace: neo-service-layer
  labels:
    app: consul
spec:
  type: ClusterIP
  ports:
    - port: 8500
      targetPort: 8500
      name: http
    - port: 8600
      targetPort: 8600
      name: dns-udp
      protocol: UDP
    - port: 8600
      targetPort: 8600
      name: dns-tcp
      protocol: TCP
  selector:
    app: consul
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: consul
  namespace: neo-service-layer
spec:
  serviceName: consul
  replicas: 3
  selector:
    matchLabels:
      app: consul
  template:
    metadata:
      labels:
        app: consul
    spec:
      containers:
        - name: consul
          image: consul:1.17
          ports:
            - containerPort: 8500
              name: http
            - containerPort: 8600
              name: dns
          env:
            - name: CONSUL_BIND_INTERFACE
              value: eth0
            - name: CONSUL_CLIENT_INTERFACE
              value: eth0
          command:
            - consul
            - agent
            - -server
            - -bootstrap-expect=3
            - -ui
            - -client=0.0.0.0
            - -retry-join=consul-0.consul.neo-service-layer.svc.cluster.local
            - -retry-join=consul-1.consul.neo-service-layer.svc.cluster.local
            - -retry-join=consul-2.consul.neo-service-layer.svc.cluster.local
          volumeMounts:
            - name: consul-data
              mountPath: /consul/data
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "200m"
  volumeClaimTemplates:
    - metadata:
        name: consul-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi