apiVersion: v1
kind: ServiceAccount
metadata:
  name: neo-service-account
  namespace: neo-service-layer
  labels:
    app: neo-service-layer
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: consul-service-account
  namespace: neo-service-layer
  labels:
    app: consul
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: neo-service-layer
  name: neo-service-role
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: neo-service-layer
  name: consul-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: neo-service-rolebinding
  namespace: neo-service-layer
subjects:
- kind: ServiceAccount
  name: neo-service-account
  namespace: neo-service-layer
roleRef:
  kind: Role
  name: neo-service-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: consul-rolebinding
  namespace: neo-service-layer
subjects:
- kind: ServiceAccount
  name: consul-service-account
  namespace: neo-service-layer
roleRef:
  kind: Role
  name: consul-role
  apiGroup: rbac.authorization.k8s.io