version: '3.8'

services:
  neo-service-layer:
    build:
      context: ../..
      dockerfile: docker/openenclave-occlum/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - /var/run/aesmd:/var/run/aesmd
    devices:
      - /dev/sgx_enclave:/dev/sgx_enclave
      - /dev/sgx_provision:/dev/sgx_provision
    environment:
      - OE_SIMULATION=1
      - OCCLUM_RELEASE_ENCLAVE=1
      - ASPNETCORE_ENVIRONMENT=Development
    restart: unless-stopped
    networks:
      - neo-network

networks:
  neo-network:
    driver: bridge
