name: Simulation Mode Tests

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'src/**'
      - 'tests/**'
      - '.github/workflows/simulation-tests.yml'
      - 'Dockerfile.test'
      - 'docker-compose.test.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'src/**'
      - 'tests/**'
      - '.github/workflows/simulation-tests.yml'
      - 'Dockerfile.test'
      - 'docker-compose.test.yml'
  workflow_dispatch:

jobs:
  test:
    name: Run Simulation Mode Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build and run tests
      run: |
        docker-compose -f docker-compose.test.yml up --build --exit-code-from simulation-tests simulation-tests
    
    - name: Upload test results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-results
        path: TestResults/
    
    - name: Process test results
      if: always()
      run: |
        # Check if any test result files exist
        if [ -d "TestResults" ] && [ "$(find TestResults -name '*.trx' | wc -l)" -gt 0 ]; then
          echo "Test results found. Processing..."
          
          # Count total tests, passed, failed, and skipped
          TOTAL_TESTS=0
          PASSED_TESTS=0
          FAILED_TESTS=0
          SKIPPED_TESTS=0
          
          for TRX_FILE in TestResults/*/*.trx; do
            if [ -f "$TRX_FILE" ]; then
              # Extract test counts using grep and sed
              TOTAL=$(grep -oP 'total="\K[0-9]+' "$TRX_FILE" || echo "0")
              PASSED=$(grep -oP 'passed="\K[0-9]+' "$TRX_FILE" || echo "0")
              FAILED=$(grep -oP 'failed="\K[0-9]+' "$TRX_FILE" || echo "0")
              SKIPPED=$(grep -oP 'notExecuted="\K[0-9]+' "$TRX_FILE" || echo "0")
              
              TOTAL_TESTS=$((TOTAL_TESTS + TOTAL))
              PASSED_TESTS=$((PASSED_TESTS + PASSED))
              FAILED_TESTS=$((FAILED_TESTS + FAILED))
              SKIPPED_TESTS=$((SKIPPED_TESTS + SKIPPED))
            fi
          done
          
          echo "::group::Test Summary"
          echo "Total Tests: $TOTAL_TESTS"
          echo "Passed: $PASSED_TESTS"
          echo "Failed: $FAILED_TESTS"
          echo "Skipped: $SKIPPED_TESTS"
          echo "::endgroup::"
          
          # Fail the workflow if any tests failed
          if [ "$FAILED_TESTS" -gt 0 ]; then
            echo "::error::$FAILED_TESTS tests failed!"
            exit 1
          else
            echo "::notice::All tests passed!"
          fi
        else
          echo "::warning::No test results found!"
          exit 1
        fi
